colors:
- [0, 238, 196]
- [98, 0, 255]
- [254, 92, 0]
- [254, 92, 0]
- [254, 154, 3]
- [255, 0, 121]
- [255, 45, 0]
- [2, 194, 255]
- [238, 240, 242]
- [7, 236, 123]
- [255, 3, 214]
- [238, 240, 242]
- [255, 45, 0]
- [0, 238, 196]
names: [Enemy, Object, Pistol, Rifle, Shotgun, Katana, Bat, Bullet, Bullet Trail,
  Submachine Gun, Railgun, Knife, Golf Club, Shuriken]
nc: 14
train: ../365295_SuperHot/images/train
val: ../365295_SuperHot/images/val
